# CONFIG FOR BASE SETUP

app:
  secret_key: "<YOUR_SECRETE_KEY_HERE>"
  jwt_secret_key: "<YOUR_SECRETE_KEY_HERE>"
  debug: true

host:
  host: "0.0.0.0"
  port: "5000"

database:
  uri: "postgres://<username>:<password>@<host>:<port>/<database>"
  check_modifications: false

logging:
  level: "INFO"
  file: "app.log"
  
weather:
 api_key: "<YOUR_API_KEY_HERE>"
 weather_url: "http://api.openweathermap.org/data/2.5/weather"
 forecast_url: "http://api.openweathermap.org/data/2.5/forecast"