# CONFIG FOR BASE SETUP

app:
  secret_key: "testnyckel"
  jwt_secret_key: "jwttestnyckel"
  max_content_length: 1048576
  debug: true

host:
  host: "0.0.0.0"
  port: "5000"

database:
  uri: "postgresql://postgres:devjohan@localhost/Jurvis"
  check_modifications: false

logging:
  level: "INFO"
  file: "app.log"
  
weather:
 api_key: "7d526ec9f3ac418d7a813e496ffc93c3"
 weather_url: "http://api.openweathermap.org/data/2.5/weather"
 forecast_url: "http://api.openweathermap.org/data/2.5/forecast"