# CONFIG FOR BASE SETUP

app:
  secret_key: "testnyckel"
  jwt_secret_key: "jwttestnyckel"
  debug: true

host:
  host: "0.0.0.0"
  port: "5000"

database:
  uri: "postgresql://postgres:devjohan@localhost/Jurvis"
  check_modifications: false

logging:
  level: "INFO"
  file: "app.log"
  